stages:
- deploy-base
- build
- deploy

build:
  stage: build
  image: registry.gitlab.tigers-mannheim.de/main/firmware/arm-none-eabi:8-2019-q3-update
  script:
  - make all
  artifacts: 
    paths:
    - release/app/run
    expire_in: 5 mins

deploy:
  stage: deploy
  image: registry.gitlab.tigers-mannheim.de/main/firmware/arm-none-eabi:8-2019-q3-update
  script:
  - ./scripts/upload.sh main2016.bin
  - ./scripts/upload.sh main2019.bin
  - ./scripts/upload.sh bs2018.bin
  - ./scripts/upload.sh ir2019.bin
  - ./scripts/upload.sh motor2019.bin
  only:
  - master
  - pipeline

deploy_arm-none-eabi:
  stage: deploy-base
  tags:
  - docker-build
  script:
  # Note: You have to change the version in the docker file first!
  - 'docker build -t registry.gitlab.tigers-mannheim.de/main/firmware/arm-none-eabi:8-2019-q3-update docker/arm-none-eabi'
  - 'docker push registry.gitlab.tigers-mannheim.de/main/firmware/arm-none-eabi:8-2019-q3-update'
  when: manual

