/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_geometry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_geometry.pb-c.h"
void   vector2f__init
                     (Vector2f         *message)
{
  static Vector2f init_value = VECTOR2F__INIT;
  *message = init_value;
}
size_t vector2f__get_packed_size
                     (const Vector2f *message)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector2f__pack
                     (const Vector2f *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector2f__pack_to_buffer
                     (const Vector2f *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vector2f *
       vector2f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vector2f *)
     protobuf_c_message_unpack (&vector2f__descriptor,
                                allocator, len, data);
}
void   vector2f__free_unpacked
                     (Vector2f *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__field_line_segment__init
                     (SSLFieldLineSegment         *message)
{
  static SSLFieldLineSegment init_value = SSL__FIELD_LINE_SEGMENT__INIT;
  *message = init_value;
}
size_t ssl__field_line_segment__get_packed_size
                     (const SSLFieldLineSegment *message)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__field_line_segment__pack
                     (const SSLFieldLineSegment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__field_line_segment__pack_to_buffer
                     (const SSLFieldLineSegment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLFieldLineSegment *
       ssl__field_line_segment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLFieldLineSegment *)
     protobuf_c_message_unpack (&ssl__field_line_segment__descriptor,
                                allocator, len, data);
}
void   ssl__field_line_segment__free_unpacked
                     (SSLFieldLineSegment *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__field_cicular_arc__init
                     (SSLFieldCicularArc         *message)
{
  static SSLFieldCicularArc init_value = SSL__FIELD_CICULAR_ARC__INIT;
  *message = init_value;
}
size_t ssl__field_cicular_arc__get_packed_size
                     (const SSLFieldCicularArc *message)
{
  assert(message->base.descriptor == &ssl__field_cicular_arc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__field_cicular_arc__pack
                     (const SSLFieldCicularArc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__field_cicular_arc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__field_cicular_arc__pack_to_buffer
                     (const SSLFieldCicularArc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__field_cicular_arc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLFieldCicularArc *
       ssl__field_cicular_arc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLFieldCicularArc *)
     protobuf_c_message_unpack (&ssl__field_cicular_arc__descriptor,
                                allocator, len, data);
}
void   ssl__field_cicular_arc__free_unpacked
                     (SSLFieldCicularArc *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__field_cicular_arc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_field_size__init
                     (SSLGeometryFieldSize         *message)
{
  static SSLGeometryFieldSize init_value = SSL__GEOMETRY_FIELD_SIZE__INIT;
  *message = init_value;
}
size_t ssl__geometry_field_size__get_packed_size
                     (const SSLGeometryFieldSize *message)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_field_size__pack
                     (const SSLGeometryFieldSize *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_field_size__pack_to_buffer
                     (const SSLGeometryFieldSize *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryFieldSize *
       ssl__geometry_field_size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryFieldSize *)
     protobuf_c_message_unpack (&ssl__geometry_field_size__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_field_size__free_unpacked
                     (SSLGeometryFieldSize *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_camera_calibration__init
                     (SSLGeometryCameraCalibration         *message)
{
  static SSLGeometryCameraCalibration init_value = SSL__GEOMETRY_CAMERA_CALIBRATION__INIT;
  *message = init_value;
}
size_t ssl__geometry_camera_calibration__get_packed_size
                     (const SSLGeometryCameraCalibration *message)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_camera_calibration__pack
                     (const SSLGeometryCameraCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_camera_calibration__pack_to_buffer
                     (const SSLGeometryCameraCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryCameraCalibration *
       ssl__geometry_camera_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryCameraCalibration *)
     protobuf_c_message_unpack (&ssl__geometry_camera_calibration__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_camera_calibration__free_unpacked
                     (SSLGeometryCameraCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_data__init
                     (SSLGeometryData         *message)
{
  static SSLGeometryData init_value = SSL__GEOMETRY_DATA__INIT;
  *message = init_value;
}
size_t ssl__geometry_data__get_packed_size
                     (const SSLGeometryData *message)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_data__pack
                     (const SSLGeometryData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_data__pack_to_buffer
                     (const SSLGeometryData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryData *
       ssl__geometry_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryData *)
     protobuf_c_message_unpack (&ssl__geometry_data__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_data__free_unpacked
                     (SSLGeometryData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vector2f__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2f, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2f, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector2f__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vector2f__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vector2f__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vector2f",
  "Vector2f",
  "Vector2f",
  "",
  sizeof(Vector2f),
  2,
  vector2f__field_descriptors,
  vector2f__field_indices_by_name,
  1,  vector2f__number_ranges,
  (ProtobufCMessageInit) vector2f__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__field_line_segment__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, p1),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, p2),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thickness",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, thickness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__field_line_segment__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = p1 */
  2,   /* field[2] = p2 */
  3,   /* field[3] = thickness */
};
static const ProtobufCIntRange ssl__field_line_segment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ssl__field_line_segment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_FieldLineSegment",
  "SSLFieldLineSegment",
  "SSLFieldLineSegment",
  "",
  sizeof(SSLFieldLineSegment),
  4,
  ssl__field_line_segment__field_descriptors,
  ssl__field_line_segment__field_indices_by_name,
  1,  ssl__field_line_segment__number_ranges,
  (ProtobufCMessageInit) ssl__field_line_segment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__field_cicular_arc__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, center),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, a1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, a2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thickness",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCicularArc, thickness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__field_cicular_arc__field_indices_by_name[] = {
  3,   /* field[3] = a1 */
  4,   /* field[4] = a2 */
  1,   /* field[1] = center */
  0,   /* field[0] = name */
  2,   /* field[2] = radius */
  5,   /* field[5] = thickness */
};
static const ProtobufCIntRange ssl__field_cicular_arc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ssl__field_cicular_arc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_FieldCicularArc",
  "SSLFieldCicularArc",
  "SSLFieldCicularArc",
  "",
  sizeof(SSLFieldCicularArc),
  6,
  ssl__field_cicular_arc__field_descriptors,
  ssl__field_cicular_arc__field_indices_by_name,
  1,  ssl__field_cicular_arc__number_ranges,
  (ProtobufCMessageInit) ssl__field_cicular_arc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_field_size__field_descriptors[7] =
{
  {
    "field_length",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, field_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_width",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, field_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, goal_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_depth",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, goal_depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boundary_width",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, boundary_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_lines",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryFieldSize, n_field_lines),
    offsetof(SSLGeometryFieldSize, field_lines),
    &ssl__field_line_segment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_arcs",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryFieldSize, n_field_arcs),
    offsetof(SSLGeometryFieldSize, field_arcs),
    &ssl__field_cicular_arc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_field_size__field_indices_by_name[] = {
  4,   /* field[4] = boundary_width */
  6,   /* field[6] = field_arcs */
  0,   /* field[0] = field_length */
  5,   /* field[5] = field_lines */
  1,   /* field[1] = field_width */
  3,   /* field[3] = goal_depth */
  2,   /* field[2] = goal_width */
};
static const ProtobufCIntRange ssl__geometry_field_size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ssl__geometry_field_size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryFieldSize",
  "SSLGeometryFieldSize",
  "SSLGeometryFieldSize",
  "",
  sizeof(SSLGeometryFieldSize),
  7,
  ssl__geometry_field_size__field_descriptors,
  ssl__geometry_field_size__field_indices_by_name,
  1,  ssl__geometry_field_size__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_field_size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_camera_calibration__field_descriptors[15] =
{
  {
    "camera_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, camera_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "focal_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, focal_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "principal_point_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, principal_point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "principal_point_y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, principal_point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distortion",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, distortion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q0",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q1",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q2",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q3",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ty",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, ty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tz",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, tz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_tx",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_tx),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_ty",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_ty),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_ty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_tz",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_tz),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_tz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_camera_calibration__field_indices_by_name[] = {
  0,   /* field[0] = camera_id */
  12,   /* field[12] = derived_camera_world_tx */
  13,   /* field[13] = derived_camera_world_ty */
  14,   /* field[14] = derived_camera_world_tz */
  4,   /* field[4] = distortion */
  1,   /* field[1] = focal_length */
  2,   /* field[2] = principal_point_x */
  3,   /* field[3] = principal_point_y */
  5,   /* field[5] = q0 */
  6,   /* field[6] = q1 */
  7,   /* field[7] = q2 */
  8,   /* field[8] = q3 */
  9,   /* field[9] = tx */
  10,   /* field[10] = ty */
  11,   /* field[11] = tz */
};
static const ProtobufCIntRange ssl__geometry_camera_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor ssl__geometry_camera_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryCameraCalibration",
  "SSLGeometryCameraCalibration",
  "SSLGeometryCameraCalibration",
  "",
  sizeof(SSLGeometryCameraCalibration),
  15,
  ssl__geometry_camera_calibration__field_descriptors,
  ssl__geometry_camera_calibration__field_indices_by_name,
  1,  ssl__geometry_camera_calibration__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_camera_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_data__field_descriptors[2] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryData, field),
    &ssl__geometry_field_size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calib",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryData, n_calib),
    offsetof(SSLGeometryData, calib),
    &ssl__geometry_camera_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_data__field_indices_by_name[] = {
  1,   /* field[1] = calib */
  0,   /* field[0] = field */
};
static const ProtobufCIntRange ssl__geometry_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssl__geometry_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryData",
  "SSLGeometryData",
  "SSLGeometryData",
  "",
  sizeof(SSLGeometryData),
  2,
  ssl__geometry_data__field_descriptors,
  ssl__geometry_data__field_indices_by_name,
  1,  ssl__geometry_data__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
