/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_refbox_log.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_refbox_log.pb-c.h"
void   log__frame__init
                     (LogFrame         *message)
{
  static LogFrame init_value = LOG__FRAME__INIT;
  *message = init_value;
}
size_t log__frame__get_packed_size
                     (const LogFrame *message)
{
  assert(message->base.descriptor == &log__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t log__frame__pack
                     (const LogFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &log__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t log__frame__pack_to_buffer
                     (const LogFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &log__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LogFrame *
       log__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LogFrame *)
     protobuf_c_message_unpack (&log__frame__descriptor,
                                allocator, len, data);
}
void   log__frame__free_unpacked
                     (LogFrame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &log__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   refbox__log__init
                     (RefboxLog         *message)
{
  static RefboxLog init_value = REFBOX__LOG__INIT;
  *message = init_value;
}
size_t refbox__log__get_packed_size
                     (const RefboxLog *message)
{
  assert(message->base.descriptor == &refbox__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t refbox__log__pack
                     (const RefboxLog *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &refbox__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t refbox__log__pack_to_buffer
                     (const RefboxLog *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &refbox__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RefboxLog *
       refbox__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RefboxLog *)
     protobuf_c_message_unpack (&refbox__log__descriptor,
                                allocator, len, data);
}
void   refbox__log__free_unpacked
                     (RefboxLog *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &refbox__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor log__frame__field_descriptors[2] =
{
  {
    "frame",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LogFrame, frame),
    &ssl__detection_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refbox_cmd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LogFrame, refbox_cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned log__frame__field_indices_by_name[] = {
  0,   /* field[0] = frame */
  1,   /* field[1] = refbox_cmd */
};
static const ProtobufCIntRange log__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor log__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Log_Frame",
  "LogFrame",
  "LogFrame",
  "",
  sizeof(LogFrame),
  2,
  log__frame__field_descriptors,
  log__frame__field_indices_by_name,
  1,  log__frame__number_ranges,
  (ProtobufCMessageInit) log__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor refbox__log__field_descriptors[1] =
{
  {
    "log",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RefboxLog, n_log),
    offsetof(RefboxLog, log),
    &log__frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned refbox__log__field_indices_by_name[] = {
  0,   /* field[0] = log */
};
static const ProtobufCIntRange refbox__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor refbox__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Refbox_Log",
  "RefboxLog",
  "RefboxLog",
  "",
  sizeof(RefboxLog),
  1,
  refbox__log__field_descriptors,
  refbox__log__field_indices_by_name,
  1,  refbox__log__number_ranges,
  (ProtobufCMessageInit) refbox__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
