/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper_legacy.proto */

#ifndef PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto__INCLUDED
#define PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "messages_robocup_ssl_detection.pb-c.h"
#include "messages_robocup_ssl_geometry_legacy.pb-c.h"

typedef struct _RoboCup2014Legacy__Wrapper__SSLWrapperPacket RoboCup2014Legacy__Wrapper__SSLWrapperPacket;


/* --- enums --- */


/* --- messages --- */

struct  _RoboCup2014Legacy__Wrapper__SSLWrapperPacket
{
  ProtobufCMessage base;
  SSLDetectionFrame *detection;
  RoboCup2014Legacy__Geometry__SSLGeometryData *geometry;
};
#define ROBO_CUP2014_LEGACY__WRAPPER__SSL__WRAPPER_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor) \
    , NULL, NULL }


/* RoboCup2014Legacy__Wrapper__SSLWrapperPacket methods */
void   robo_cup2014_legacy__wrapper__ssl__wrapper_packet__init
                     (RoboCup2014Legacy__Wrapper__SSLWrapperPacket         *message);
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__get_packed_size
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket   *message);
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__pack
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket   *message,
                      uint8_t             *out);
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__pack_to_buffer
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket   *message,
                      ProtobufCBuffer     *buffer);
RoboCup2014Legacy__Wrapper__SSLWrapperPacket *
       robo_cup2014_legacy__wrapper__ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robo_cup2014_legacy__wrapper__ssl__wrapper_packet__free_unpacked
                     (RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RoboCup2014Legacy__Wrapper__SSLWrapperPacket_Closure)
                 (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_5flegacy_2eproto__INCLUDED */
