/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_geometry_legacy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_geometry_legacy.pb-c.h"
void   robo_cup2014_legacy__geometry__ssl__geometry_field_size__init
                     (RoboCup2014Legacy__Geometry__SSLGeometryFieldSize         *message)
{
  static RoboCup2014Legacy__Geometry__SSLGeometryFieldSize init_value = ROBO_CUP2014_LEGACY__GEOMETRY__SSL__GEOMETRY_FIELD_SIZE__INIT;
  *message = init_value;
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__get_packed_size
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__pack
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__pack_to_buffer
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *
       robo_cup2014_legacy__geometry__ssl__geometry_field_size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *)
     protobuf_c_message_unpack (&robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor,
                                allocator, len, data);
}
void   robo_cup2014_legacy__geometry__ssl__geometry_field_size__free_unpacked
                     (RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robo_cup2014_legacy__geometry__ssl__geometry_data__init
                     (RoboCup2014Legacy__Geometry__SSLGeometryData         *message)
{
  static RoboCup2014Legacy__Geometry__SSLGeometryData init_value = ROBO_CUP2014_LEGACY__GEOMETRY__SSL__GEOMETRY_DATA__INIT;
  *message = init_value;
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__get_packed_size
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData *message)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__pack
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__pack_to_buffer
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoboCup2014Legacy__Geometry__SSLGeometryData *
       robo_cup2014_legacy__geometry__ssl__geometry_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoboCup2014Legacy__Geometry__SSLGeometryData *)
     protobuf_c_message_unpack (&robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor,
                                allocator, len, data);
}
void   robo_cup2014_legacy__geometry__ssl__geometry_data__free_unpacked
                     (RoboCup2014Legacy__Geometry__SSLGeometryData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor robo_cup2014_legacy__geometry__ssl__geometry_field_size__field_descriptors[14] =
{
  {
    "line_width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, line_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, field_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, field_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boundary_width",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, boundary_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "referee_width",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, referee_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_width",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, goal_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_depth",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, goal_depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_wall_width",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, goal_wall_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center_circle_radius",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, center_circle_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defense_radius",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, defense_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defense_stretch",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, defense_stretch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "free_kick_from_defense_dist",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, free_kick_from_defense_dist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "penalty_spot_from_field_line_dist",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, penalty_spot_from_field_line_dist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "penalty_line_from_spot_dist",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize, penalty_line_from_spot_dist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robo_cup2014_legacy__geometry__ssl__geometry_field_size__field_indices_by_name[] = {
  3,   /* field[3] = boundary_width */
  8,   /* field[8] = center_circle_radius */
  9,   /* field[9] = defense_radius */
  10,   /* field[10] = defense_stretch */
  1,   /* field[1] = field_length */
  2,   /* field[2] = field_width */
  11,   /* field[11] = free_kick_from_defense_dist */
  6,   /* field[6] = goal_depth */
  7,   /* field[7] = goal_wall_width */
  5,   /* field[5] = goal_width */
  0,   /* field[0] = line_width */
  13,   /* field[13] = penalty_line_from_spot_dist */
  12,   /* field[12] = penalty_spot_from_field_line_dist */
  4,   /* field[4] = referee_width */
};
static const ProtobufCIntRange robo_cup2014_legacy__geometry__ssl__geometry_field_size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoboCup2014Legacy.Geometry.SSL_GeometryFieldSize",
  "SSLGeometryFieldSize",
  "RoboCup2014Legacy__Geometry__SSLGeometryFieldSize",
  "RoboCup2014Legacy.Geometry",
  sizeof(RoboCup2014Legacy__Geometry__SSLGeometryFieldSize),
  14,
  robo_cup2014_legacy__geometry__ssl__geometry_field_size__field_descriptors,
  robo_cup2014_legacy__geometry__ssl__geometry_field_size__field_indices_by_name,
  1,  robo_cup2014_legacy__geometry__ssl__geometry_field_size__number_ranges,
  (ProtobufCMessageInit) robo_cup2014_legacy__geometry__ssl__geometry_field_size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robo_cup2014_legacy__geometry__ssl__geometry_data__field_descriptors[2] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryData, field),
    &robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calib",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryData, n_calib),
    offsetof(RoboCup2014Legacy__Geometry__SSLGeometryData, calib),
    &ssl__geometry_camera_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robo_cup2014_legacy__geometry__ssl__geometry_data__field_indices_by_name[] = {
  1,   /* field[1] = calib */
  0,   /* field[0] = field */
};
static const ProtobufCIntRange robo_cup2014_legacy__geometry__ssl__geometry_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoboCup2014Legacy.Geometry.SSL_GeometryData",
  "SSLGeometryData",
  "RoboCup2014Legacy__Geometry__SSLGeometryData",
  "RoboCup2014Legacy.Geometry",
  sizeof(RoboCup2014Legacy__Geometry__SSLGeometryData),
  2,
  robo_cup2014_legacy__geometry__ssl__geometry_data__field_descriptors,
  robo_cup2014_legacy__geometry__ssl__geometry_data__field_indices_by_name,
  1,  robo_cup2014_legacy__geometry__ssl__geometry_data__number_ranges,
  (ProtobufCMessageInit) robo_cup2014_legacy__geometry__ssl__geometry_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
