/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_detection.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_detection.pb-c.h"
void   ssl__detection_ball__init
                     (SSLDetectionBall         *message)
{
  static SSLDetectionBall init_value = SSL__DETECTION_BALL__INIT;
  *message = init_value;
}
size_t ssl__detection_ball__get_packed_size
                     (const SSLDetectionBall *message)
{
  assert(message->base.descriptor == &ssl__detection_ball__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__detection_ball__pack
                     (const SSLDetectionBall *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__detection_ball__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__detection_ball__pack_to_buffer
                     (const SSLDetectionBall *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__detection_ball__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLDetectionBall *
       ssl__detection_ball__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLDetectionBall *)
     protobuf_c_message_unpack (&ssl__detection_ball__descriptor,
                                allocator, len, data);
}
void   ssl__detection_ball__free_unpacked
                     (SSLDetectionBall *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__detection_ball__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__detection_robot__init
                     (SSLDetectionRobot         *message)
{
  static SSLDetectionRobot init_value = SSL__DETECTION_ROBOT__INIT;
  *message = init_value;
}
size_t ssl__detection_robot__get_packed_size
                     (const SSLDetectionRobot *message)
{
  assert(message->base.descriptor == &ssl__detection_robot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__detection_robot__pack
                     (const SSLDetectionRobot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__detection_robot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__detection_robot__pack_to_buffer
                     (const SSLDetectionRobot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__detection_robot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLDetectionRobot *
       ssl__detection_robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLDetectionRobot *)
     protobuf_c_message_unpack (&ssl__detection_robot__descriptor,
                                allocator, len, data);
}
void   ssl__detection_robot__free_unpacked
                     (SSLDetectionRobot *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__detection_robot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__detection_frame__init
                     (SSLDetectionFrame         *message)
{
  static SSLDetectionFrame init_value = SSL__DETECTION_FRAME__INIT;
  *message = init_value;
}
size_t ssl__detection_frame__get_packed_size
                     (const SSLDetectionFrame *message)
{
  assert(message->base.descriptor == &ssl__detection_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__detection_frame__pack
                     (const SSLDetectionFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__detection_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__detection_frame__pack_to_buffer
                     (const SSLDetectionFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__detection_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLDetectionFrame *
       ssl__detection_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLDetectionFrame *)
     protobuf_c_message_unpack (&ssl__detection_frame__descriptor,
                                allocator, len, data);
}
void   ssl__detection_frame__free_unpacked
                     (SSLDetectionFrame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__detection_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssl__detection_ball__field_descriptors[7] =
{
  {
    "confidence",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionBall, confidence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "area",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SSLDetectionBall, has_area),
    offsetof(SSLDetectionBall, area),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionBall, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionBall, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLDetectionBall, has_z),
    offsetof(SSLDetectionBall, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_x",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionBall, pixel_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_y",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionBall, pixel_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__detection_ball__field_indices_by_name[] = {
  1,   /* field[1] = area */
  0,   /* field[0] = confidence */
  5,   /* field[5] = pixel_x */
  6,   /* field[6] = pixel_y */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
  4,   /* field[4] = z */
};
static const ProtobufCIntRange ssl__detection_ball__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ssl__detection_ball__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_DetectionBall",
  "SSLDetectionBall",
  "SSLDetectionBall",
  "",
  sizeof(SSLDetectionBall),
  7,
  ssl__detection_ball__field_descriptors,
  ssl__detection_ball__field_indices_by_name,
  1,  ssl__detection_ball__number_ranges,
  (ProtobufCMessageInit) ssl__detection_ball__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__detection_robot__field_descriptors[8] =
{
  {
    "confidence",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionRobot, confidence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robot_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SSLDetectionRobot, has_robot_id),
    offsetof(SSLDetectionRobot, robot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionRobot, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionRobot, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orientation",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLDetectionRobot, has_orientation),
    offsetof(SSLDetectionRobot, orientation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_x",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionRobot, pixel_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_y",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionRobot, pixel_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLDetectionRobot, has_height),
    offsetof(SSLDetectionRobot, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__detection_robot__field_indices_by_name[] = {
  0,   /* field[0] = confidence */
  7,   /* field[7] = height */
  4,   /* field[4] = orientation */
  5,   /* field[5] = pixel_x */
  6,   /* field[6] = pixel_y */
  1,   /* field[1] = robot_id */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange ssl__detection_robot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ssl__detection_robot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_DetectionRobot",
  "SSLDetectionRobot",
  "SSLDetectionRobot",
  "",
  sizeof(SSLDetectionRobot),
  8,
  ssl__detection_robot__field_descriptors,
  ssl__detection_robot__field_indices_by_name,
  1,  ssl__detection_robot__number_ranges,
  (ProtobufCMessageInit) ssl__detection_robot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__detection_frame__field_descriptors[7] =
{
  {
    "frame_number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionFrame, frame_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_capture",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionFrame, t_capture),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_sent",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionFrame, t_sent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SSLDetectionFrame, camera_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balls",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLDetectionFrame, n_balls),
    offsetof(SSLDetectionFrame, balls),
    &ssl__detection_ball__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robots_yellow",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLDetectionFrame, n_robots_yellow),
    offsetof(SSLDetectionFrame, robots_yellow),
    &ssl__detection_robot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robots_blue",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLDetectionFrame, n_robots_blue),
    offsetof(SSLDetectionFrame, robots_blue),
    &ssl__detection_robot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__detection_frame__field_indices_by_name[] = {
  4,   /* field[4] = balls */
  3,   /* field[3] = camera_id */
  0,   /* field[0] = frame_number */
  6,   /* field[6] = robots_blue */
  5,   /* field[5] = robots_yellow */
  1,   /* field[1] = t_capture */
  2,   /* field[2] = t_sent */
};
static const ProtobufCIntRange ssl__detection_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ssl__detection_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_DetectionFrame",
  "SSLDetectionFrame",
  "SSLDetectionFrame",
  "",
  sizeof(SSLDetectionFrame),
  7,
  ssl__detection_frame__field_descriptors,
  ssl__detection_frame__field_indices_by_name,
  1,  ssl__detection_frame__number_ranges,
  (ProtobufCMessageInit) ssl__detection_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
