/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper.proto */

#ifndef PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED
#define PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "messages_robocup_ssl_detection.pb-c.h"
#include "messages_robocup_ssl_geometry.pb-c.h"

typedef struct _SSLWrapperPacket SSLWrapperPacket;


/* --- enums --- */


/* --- messages --- */

struct  _SSLWrapperPacket
{
  ProtobufCMessage base;
  SSLDetectionFrame *detection;
  SSLGeometryData *geometry;
};
#define SSL__WRAPPER_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssl__wrapper_packet__descriptor) \
    , NULL, NULL }


/* SSLWrapperPacket methods */
void   ssl__wrapper_packet__init
                     (SSLWrapperPacket         *message);
size_t ssl__wrapper_packet__get_packed_size
                     (const SSLWrapperPacket   *message);
size_t ssl__wrapper_packet__pack
                     (const SSLWrapperPacket   *message,
                      uint8_t             *out);
size_t ssl__wrapper_packet__pack_to_buffer
                     (const SSLWrapperPacket   *message,
                      ProtobufCBuffer     *buffer);
SSLWrapperPacket *
       ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssl__wrapper_packet__free_unpacked
                     (SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SSLWrapperPacket_Closure)
                 (const SSLWrapperPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssl__wrapper_packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED */
