/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper_legacy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_wrapper_legacy.pb-c.h"
void   robo_cup2014_legacy__wrapper__ssl__wrapper_packet__init
                     (RoboCup2014Legacy__Wrapper__SSLWrapperPacket         *message)
{
  static RoboCup2014Legacy__Wrapper__SSLWrapperPacket init_value = ROBO_CUP2014_LEGACY__WRAPPER__SSL__WRAPPER_PACKET__INIT;
  *message = init_value;
}
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__get_packed_size
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__pack
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robo_cup2014_legacy__wrapper__ssl__wrapper_packet__pack_to_buffer
                     (const RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoboCup2014Legacy__Wrapper__SSLWrapperPacket *
       robo_cup2014_legacy__wrapper__ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoboCup2014Legacy__Wrapper__SSLWrapperPacket *)
     protobuf_c_message_unpack (&robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor,
                                allocator, len, data);
}
void   robo_cup2014_legacy__wrapper__ssl__wrapper_packet__free_unpacked
                     (RoboCup2014Legacy__Wrapper__SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor robo_cup2014_legacy__wrapper__ssl__wrapper_packet__field_descriptors[2] =
{
  {
    "detection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Wrapper__SSLWrapperPacket, detection),
    &ssl__detection_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RoboCup2014Legacy__Wrapper__SSLWrapperPacket, geometry),
    &robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robo_cup2014_legacy__wrapper__ssl__wrapper_packet__field_indices_by_name[] = {
  0,   /* field[0] = detection */
  1,   /* field[1] = geometry */
};
static const ProtobufCIntRange robo_cup2014_legacy__wrapper__ssl__wrapper_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor robo_cup2014_legacy__wrapper__ssl__wrapper_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoboCup2014Legacy.Wrapper.SSL_WrapperPacket",
  "SSLWrapperPacket",
  "RoboCup2014Legacy__Wrapper__SSLWrapperPacket",
  "RoboCup2014Legacy.Wrapper",
  sizeof(RoboCup2014Legacy__Wrapper__SSLWrapperPacket),
  2,
  robo_cup2014_legacy__wrapper__ssl__wrapper_packet__field_descriptors,
  robo_cup2014_legacy__wrapper__ssl__wrapper_packet__field_indices_by_name,
  1,  robo_cup2014_legacy__wrapper__ssl__wrapper_packet__number_ranges,
  (ProtobufCMessageInit) robo_cup2014_legacy__wrapper__ssl__wrapper_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
