/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_wrapper.pb-c.h"
void   ssl__wrapper_packet__init
                     (SSLWrapperPacket         *message)
{
  static SSLWrapperPacket init_value = SSL__WRAPPER_PACKET__INIT;
  *message = init_value;
}
size_t ssl__wrapper_packet__get_packed_size
                     (const SSLWrapperPacket *message)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__wrapper_packet__pack
                     (const SSLWrapperPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__wrapper_packet__pack_to_buffer
                     (const SSLWrapperPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLWrapperPacket *
       ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLWrapperPacket *)
     protobuf_c_message_unpack (&ssl__wrapper_packet__descriptor,
                                allocator, len, data);
}
void   ssl__wrapper_packet__free_unpacked
                     (SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssl__wrapper_packet__field_descriptors[2] =
{
  {
    "detection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLWrapperPacket, detection),
    &ssl__detection_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLWrapperPacket, geometry),
    &ssl__geometry_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__wrapper_packet__field_indices_by_name[] = {
  0,   /* field[0] = detection */
  1,   /* field[1] = geometry */
};
static const ProtobufCIntRange ssl__wrapper_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssl__wrapper_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_WrapperPacket",
  "SSLWrapperPacket",
  "SSLWrapperPacket",
  "",
  sizeof(SSLWrapperPacket),
  2,
  ssl__wrapper_packet__field_descriptors,
  ssl__wrapper_packet__field_indices_by_name,
  1,  ssl__wrapper_packet__number_ranges,
  (ProtobufCMessageInit) ssl__wrapper_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
