/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_geometry_legacy.proto */

#ifndef PROTOBUF_C_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto__INCLUDED
#define PROTOBUF_C_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "messages_robocup_ssl_geometry.pb-c.h"

typedef struct _RoboCup2014Legacy__Geometry__SSLGeometryFieldSize RoboCup2014Legacy__Geometry__SSLGeometryFieldSize;
typedef struct _RoboCup2014Legacy__Geometry__SSLGeometryData RoboCup2014Legacy__Geometry__SSLGeometryData;


/* --- enums --- */


/* --- messages --- */

struct  _RoboCup2014Legacy__Geometry__SSLGeometryFieldSize
{
  ProtobufCMessage base;
  int32_t line_width;
  int32_t field_length;
  int32_t field_width;
  int32_t boundary_width;
  int32_t referee_width;
  int32_t goal_width;
  int32_t goal_depth;
  int32_t goal_wall_width;
  int32_t center_circle_radius;
  int32_t defense_radius;
  int32_t defense_stretch;
  int32_t free_kick_from_defense_dist;
  int32_t penalty_spot_from_field_line_dist;
  int32_t penalty_line_from_spot_dist;
};
#define ROBO_CUP2014_LEGACY__GEOMETRY__SSL__GEOMETRY_FIELD_SIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _RoboCup2014Legacy__Geometry__SSLGeometryData
{
  ProtobufCMessage base;
  RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *field;
  size_t n_calib;
  SSLGeometryCameraCalibration **calib;
};
#define ROBO_CUP2014_LEGACY__GEOMETRY__SSL__GEOMETRY_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor) \
    , NULL, 0,NULL }


/* RoboCup2014Legacy__Geometry__SSLGeometryFieldSize methods */
void   robo_cup2014_legacy__geometry__ssl__geometry_field_size__init
                     (RoboCup2014Legacy__Geometry__SSLGeometryFieldSize         *message);
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__get_packed_size
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize   *message);
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__pack
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize   *message,
                      uint8_t             *out);
size_t robo_cup2014_legacy__geometry__ssl__geometry_field_size__pack_to_buffer
                     (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize   *message,
                      ProtobufCBuffer     *buffer);
RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *
       robo_cup2014_legacy__geometry__ssl__geometry_field_size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robo_cup2014_legacy__geometry__ssl__geometry_field_size__free_unpacked
                     (RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message,
                      ProtobufCAllocator *allocator);
/* RoboCup2014Legacy__Geometry__SSLGeometryData methods */
void   robo_cup2014_legacy__geometry__ssl__geometry_data__init
                     (RoboCup2014Legacy__Geometry__SSLGeometryData         *message);
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__get_packed_size
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData   *message);
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__pack
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData   *message,
                      uint8_t             *out);
size_t robo_cup2014_legacy__geometry__ssl__geometry_data__pack_to_buffer
                     (const RoboCup2014Legacy__Geometry__SSLGeometryData   *message,
                      ProtobufCBuffer     *buffer);
RoboCup2014Legacy__Geometry__SSLGeometryData *
       robo_cup2014_legacy__geometry__ssl__geometry_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robo_cup2014_legacy__geometry__ssl__geometry_data__free_unpacked
                     (RoboCup2014Legacy__Geometry__SSLGeometryData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RoboCup2014Legacy__Geometry__SSLGeometryFieldSize_Closure)
                 (const RoboCup2014Legacy__Geometry__SSLGeometryFieldSize *message,
                  void *closure_data);
typedef void (*RoboCup2014Legacy__Geometry__SSLGeometryData_Closure)
                 (const RoboCup2014Legacy__Geometry__SSLGeometryData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor robo_cup2014_legacy__geometry__ssl__geometry_field_size__descriptor;
extern const ProtobufCMessageDescriptor robo_cup2014_legacy__geometry__ssl__geometry_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_5frobocup_5fssl_5fgeometry_5flegacy_2eproto__INCLUDED */
