set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_PREFIX_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
find_program(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}g++")
find_program(CMAKE_MAKE_PROGRAM "make")
find_program(CMAKE_OBJCOPY "${TOOLCHAIN_PREFIX}objcopy")
find_program(TOOL_SIZE_UTIL "${TOOLCHAIN_PREFIX}size")
find_program(TOOL_HEX2DFU "hex2dfu")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
